### ISSUE TITLE
Ask for paper

### ISSUE THREAD

**Issue by latuanvinh1998** [acmmmsys/2021-grandchallenge-cheapfakes-cosmosonsteroids#1]
Hi, if it possible, can you send me your paper through email latuanvinh1998@gmail.com. 
Thank you very much.

**Comment by cise-midoglu** [comment]
You can find the MMSys'21 Grand Challenge on Detecting Cheapfakes:
- challenge overview paper here: https://arxiv.org/abs/2107.05297
- submission from Akgul et al. here: https://dl.acm.org/doi/10.1145/3458305.3479968
