### ISSUE TITLE
Please share the dataset

### ISSUE THREAD

**Issue by 963149408** [acmmmsys/2021-grandchallenge-cheapfakes-cosmosonsteroids#2]
I am a graduate student from Chengdu University of Information Technolgy in China.  I am currently learning NLP and have finished reading your paper "COSMOS: Catching Out-of-Context Misinformation with Self-Supervised Learning", however, I am unable to download the dataset.  Could you be so kind as to share it with me? It would greatly appreciate it.  My google account is z978768269@gmail.com.  Thank you for youor consideration!

**Comment by cise-midoglu** [comment]
The Grand Challenge on Detecting Cheapfakes is now hosted by the ACM Multimedia Conference. 
Please feel free to request the dataset using the form on the challenge page: https://detecting-cheapfakes.github.io
