### ISSUE TITLE
Problems with `model_archs/image/image_models.py`

### ISSUE THREAD

**Issue by vanloc1808** [acmmmsys/2021-grandchallenge-cheapfakes-cosmosonsteroids#3]
Hi guys,
It has been so long since your work, I have tried 
```
python trainer_script.py -m train
```
but I got some errors :(
First, if I keep the code
```
bbox_feats = torch.stack(
            [self.maskrcnn_predictor(img.cpu().numpy(), target) for img, target in zip(imgs, targets)])
```
I got (see the below images):
```
TypeError: __call__() takes 2 positional arguments but 3 were given
```
![image](https://github.com/acmmmsys/2021-grandchallenge-cheapfakes-cosmosonsteroids/assets/76842571/23010d49-d49f-4220-ac36-49fa00686c3e)
Second, I tried removing `target`, now the code became
```
bbox_feats = torch.stack(
            [self.maskrcnn_predictor(img.cpu().numpy()) for img, target in zip(imgs, targets)])
```
I did not get the above error anymore, but I got:
```
TypeError: expected Tensor as element 0 in argument 0, but got dict
```
![image](https://github.com/acmmmsys/2021-grandchallenge-cheapfakes-cosmosonsteroids/assets/76842571/e8e60407-8cb3-4ad3-8e67-7895d7447bef)
Now, I guessed the problem with `.numpy()` function call, so I tried removing it, the code became:

```
bbox_feats = torch.stack(
            [self.maskrcnn_predictor(img.cpu()) for img, target in zip(imgs, targets)])
```
At here I got 
```
AttributeError: 'Tensor' object has no attribute 'strides'
```
![image](https://github.com/acmmmsys/2021-grandchallenge-cheapfakes-cosmosonsteroids/assets/76842571/851245b2-2926-4d2d-97c9-5fe68aa16de9)
Could you please take a look? I don't know where the cause is from :(

**Comment by DenizUgur** [comment]
If Docker version is working then I'd assume some sort of version incompatibility might be happening. Could you verify if that one works?

**Comment by DenizUgur** [comment]
Try the prebuilt image here: https://github.com/DenizUgur/COSMOS/pkgs/container/mmsys21cheapfakes

**Comment by vanloc1808** [comment]
@DenizUgur it seems that the link is a private repo
![image](https://github.com/acmmmsys/2021-grandchallenge-cheapfakes-cosmosonsteroids/assets/76842571/3db68f05-3639-45ea-8afa-3fdd69dd46a1)
Moreover, by here I want a custom training :( so I'm finding a way to run the training code :(

**Comment by DenizUgur** [comment]
Sorry for that. Repository was public but apperantly the package was private. Please try it again.

> so I'm finding a way to run the training code :(

Your best bet is to start from the existing image and see which version or package started the issues you are seeing. It's been almost 3 years so it's no surprise it's not working with the newest versions.
